version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: my_nginx_container
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/deme.blobcart.com/fullchain.pem:/etc/letsencrypt/live/deme.blobcart.com/fullchain.pem
      - /etc/letsencrypt/live/deme.blobcart.com/privkey.pem:/etc/letsencrypt/live/deme.blobcart.com/privkey.pem
    depends_on:
      - backend




  backend:
    container_name: backend-dev
    image: codenames-backend
    restart: unless-stopped
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    platform: linux/x86_64

 

  
