version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: my_nginx_container
    ports:
      - "80:80"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network
    depends_on:
      - backend




  backend:
    container_name: backend-dev
    image: codenames-backend
    restart: unless-stopped
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - shared-network
    volumes:
      - ./backend:/backend
    platform: linux/x86_64

 

  
networks:
  shared-network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16  # Specify the desired subnet



